# Generated by Django 2.0.6 on 2018-11-29 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiceA', models.CharField(blank=True, max_length=30, unique=True)),
                ('password', models.CharField(blank=True, max_length=30)),
                ('nome', models.CharField(blank=True, max_length=30)),
                ('ragionesociale', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CronologiaPunti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transazione', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiceU', models.CharField(max_length=30, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('punti', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='cronologiapunti',
            name='codice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewind.Utente'),
        ),
    ]
