# Generated by Django 2.0.6 on 2018-11-29 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rewind', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodiciRegistrazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Azienda',
        ),
        migrations.RenameField(
            model_name='cronologiapunti',
            old_name='codice',
            new_name='utente',
        ),
        migrations.RenameField(
            model_name='utente',
            old_name='codiceU',
            new_name='codice_utente',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='password',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='username',
        ),
        migrations.AddField(
            model_name='cronologiapunti',
            name='punti_spesi',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utente',
            name='cap',
            field=models.IntegerField(blank=True, default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utente',
            name='citta',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='utente',
            name='n_componenti',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='utente',
            name='tipologia',
            field=models.TextField(blank=True, choices=[('', '-----------------'), ('mono', 'monolocale'), ('bil', 'bilocale'), ('tri', 'trilocale/appartamento'), ('abind', 'abitazione indipendente')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='utente',
            name='user',
            field=models.OneToOneField(default=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utente',
            name='via',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
