# Generated by Django 2.0.6 on 2018-11-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewind', '0002_auto_20181129_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='cap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
