# Generated by Django 2.0.6 on 2018-11-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewind', '0003_auto_20181129_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codiciregistrazione',
            name='codice',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
