# Generated by Django 2.0.6 on 2018-11-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewind', '0005_auto_20181129_1912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodiciRegistrazione',
        ),
        migrations.RemoveField(
            model_name='cronologiapunti',
            name='utente',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='CronologiaPunti',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
